# 容器服務
services:
  # 容器片段名稱
  web:
    build:
      # 從 web 目錄中，依據 Dockerfile 檔來建立映像檔
      context: ./web
    ports:
      # [host port]:[container port]
      - "8080:8000"
    volumes:
      # [host: web 資料夾] 對應到 [container: /var/www/localhost/htdocs/my_proj]
      - ./web:/var/www/localhost/htdocs/my_proj
    networks:
      # 將此容器加進 my_network 網路
      my_network:
  db:
    build:
      context: ./db
    ports:
      - "8806:3306"
    # 如果容器異常退出，會自動重啟
    restart: always
    environment:
      # 讀取 .env 檔的 MARIADB_ROOT_PASSWORD
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      # [host: db/data 資料夾] 對應到 [container: /var/lib/mysql]
      - ./db/data:/var/lib/mysql
    networks:
      # 將此容器加進 my_network 網路
      my_network:

networks:
  # 自定義網路名稱叫做 my_network
  my_network: